<<<<<<< HEAD
custom: ['https://www.paypal.com/paypalme/yurinkonstantin']
=======
custom: ['https://reactos.org/donate/', 'https://www.paypal.me/ReactOS']
>>>>>>> 474a8ea46bec44a9155194ef2bf92548a9bfca07
